### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'ZMQSocketException' with message 'Failed to send message: Interrupted system call'

### ISSUE THREAD

**Issue by cmosguy** [zeromq/php-zmq#141]
I am not sure what I could possibly be doing wrong here.  I am implementing a simple zmq message into my ratchet websocket framework.  

I am getting the error message:

``` bash
PHP Fatal error:  Uncaught exception 'ZMQSocketException' with message 'Failed to send message: Interrupted system call'
```

Not sure what I am doing wrong here.  Here is the server code:

``` php
  //Listen for web server to make ZeroMQ push after an ajax request
        $context = new Context($loop);

        $pull = $context->getSocket(\ZMQ::SOCKET_PULL);
        $pull->bind(\Config::get('squarekings.zmqserver') . ':' . $port); // Binding to 127.0.0.1 means the only client that can connect is itself
        $pull->on('message', array($pusher, 'onGameUpdate'));
        $pull->on('square', array($pusher, 'onSquareUpdate'));


        // Set up our WebSocket server for clients wanting real-time updates
        $webSock = new Server($loop);
        $webSock->listen(8080, '0.0.0.0'); // Binding to 0.0.0.0 means remotes can connect
        $webServer = new IoServer(
            new HttpServer(
                new WsServer(
                    new WampServer(
                        $pusher
                    )
                )
            ),
            $webSock
        );
```

Then when i am trying to send the message or update for the request I have the following:

``` php
  $this->socket = $context->getSocket(\ZMQ::SOCKET_PUSH, 'my pusher');
            $this->socket->connect(\Config::get('squarekings.zmqserver') . ":" . \Config::get('squarekings.zmqport'));
 $this->socket->send(json_encode($arr));
```

I don't understand how to debug this and what is going on with the handling of the ZMQ messages.  Can someone please advise how I could fix this issue?

Thanks!

**Comment by Rastusik** [comment]
@cmosguy I have the same problem when using ZMQ with Swoole (which seems to fork php processes) ... Is this extension compatible with such a use case?

**Comment by duckboy81** [comment]
Not to turn this into stackoverflow, but for future folks finding themselves here, you may seek to reorganize your code to `bind` or `connect` AFTER your fork occurs.

Moving my `$rep->connect("ipc://" . self::ZQM_SOCKET_PATH);` to a function call after I forked has solved the problem.

**Comment by Rastusik** [comment]
yeah, I figured that as well, but I think, that that's just a workaround, isn't it?
