### ISSUE TITLE
Update to 4.x zeromq?

### ISSUE THREAD

**Issue by WyoMurf** [zeromq/php-zmq#182]
Any plans to update to 4.x of zeromq... I'd kinda like to set the Connect timeout...

**Comment by steinmb** [comment]
Wonder the same. 4.0.x got release `0MQ version 4.0.1 stable, released on 2013/10/08` - https://raw.githubusercontent.com/zeromq/zeromq4-x/master/NEWS

**Comment by zebastian** [comment]
@WyoMurf @steinmb this is present now in current master branch.
release is still pending
