### ISSUE TITLE
Please fix bug links in pecl

### ISSUE THREAD

**Issue by remicollet** [zeromq/php-zmq#192]
On
https://pecl.php.net/package/zmq

*  Package Bugs => https://bugs.php.net/search.php?cmd=display&status=Open&package_name[]=zmq
* Report new bug => https://bugs.php.net/report.php?package=zmq

Please use the "edit" button to set bug tracker to https://github.com/mkoppanen/php-zmq/issues

**Comment by cmb69** [comment]
I've just did that. Also added the documentation link, and marked the package as umaintained (looking for a new maintainer; hopefully someone steps up).

So this ticket could be closed.
