### ISSUE TITLE
Move php-zmq under an organisation

### ISSUE THREAD

**Issue by mkoppanen** [zeromq/php-zmq#198]
I don't actively work on PHP related projects at this point and would like to move this under extension under an organisation that can take over the management. I am happy to either set up a new organisation for random PHP extensions I used to work on or move this under another organisation.

Suggestions?

**Comment by bluca** [comment]
Hi,

I really know nothing about PHP and thus can't promise help with support, however we would be delighted if you wanted to move php-zmq under the zeromq org: https://github.com/zeromq - you (and/or any other future maintainer) would of course be invited to join and keep admin privileges on the repository. Does this sound like a good option for you?

Also I would be happy to do a "call for maintainers" on the zeromq mailing list, if you wish.

Thanks for your work on this project!

**Comment by remicollet** [comment]
Why not simply move to git.php.net, as some other extensions ?

This will allow some PHP developers to fix sources when needed.
Only need some new "lead" to run the release process.

**Comment by need-sleep** [comment]
@bluca 's suggestion is likely best. php-zmq is not a simple set of wrappers to glue an existing zmq solution into PHP. It will require at least one person fully knowledgeable of all of zmq's underlying concepts and protocols (libcurve for example, not just user-space push/pull, ect.). php-zmq is maybe 2% PHP specific, with most of this code being entry level extension code that most competent C/C++ developers can grasp within a couple hours of reading. It's php stream wrappers are more advanced but even those are simple in nature. The other 98% is low-level libzmq bindings, putting it squarely in the zmq domain making the zmq community the proper place IMO.

**Comment by nikic** [comment]
Moving this to the zeromq org sounds like a great idea, it seems that there are already many other language-specific bindings there :)

**Comment by bluinkltd** [comment]
Any progress on this? Would be great to see a new release on PECL

**Comment by mkoppanen** [comment]
@bluca,

I think the idea of moving this under zeromq organisation sounds like the best idea to me.

**Comment by mkoppanen** [comment]
@bluca,

looks like github doesn't handle the "transfer request" unless you have access to the organisation (You don’t have the permission to create repositories on zeromq). How do we go about this process?

**Comment by bluca** [comment]
I've sent you the invitation to join the org, you should be able to move it then - I'll then give you admin permissions on the repository (if the process doesn't do that already). Please enable 2FA if you haven't already

**Comment by bluca** [comment]
@mkoppanen did the invitation arrive?

**Comment by mkoppanen** [comment]
@bluca,

The transfer should be complete now. Thank you for your assistance on this!

**Comment by bluca** [comment]
@mkoppanen great, thanks! I have given you admin rights on the repository - is there another maintainer you'd like to add? Would you like to send an announcement to zeromq-dev mailing list, asking for new collaborators?

**Comment by mikesi** [comment]
Nice to see some progress here, will make to move to 7.3 much easier then.

**Comment by bluca** [comment]
I will do a call for maintainers via the mailing list - @mkoppanen if you have a suggestion and would like to name a "volunteer" please let me know and I'll go pester them :-)

**Comment by bluca** [comment]
Posted to the mailing list: https://lists.zeromq.org/pipermail/zeromq-dev/2019-August/033109.html
