### ISSUE TITLE
Compilation error: expression is not assignable  (MacOS, php 7.3)

### ISSUE THREAD

**Issue by inikoo** [zeromq/php-zmq#199]
cc -I. -I/Users/x/tmp/php-zmq -DPHP_ATOM_INC -I/Users/x/tmp/php-zmq/include -I/Users/x/tmp/php-zmq/main -I/Users/x/tmp/php-zmq -I/usr/local/Cellar/php/7.3.2/include/php -I/usr/local/Cellar/php/7.3.2/include/php/main -I/usr/local/Cellar/php/7.3.2/include/php/TSRM -I/usr/local/Cellar/php/7.3.2/include/php/Zend -I/usr/local/Cellar/php/7.3.2/include/php/ext -I/usr/local/Cellar/php/7.3.2/include/php/ext/date/lib -I/usr/local/Cellar/zeromq/4.3.1_1/include -DHAVE_CONFIG_H -g -O2 -c /Users/x/tmp/php-zmq/zmq.c  -fno-common -DPIC -o .libs/zmq.o

/Users/x/tmp/php-zmq/zmq.c:210:50: warning: format specifies type 'long' but the argument has type 'zend_long' (aka 'long long') [-Wformat]
                plist_key = strpprintf(0, "zmq_context=[%ld]", io_threads);
                                                        ~~~    ^~~~~~~~~~
                                                        %lld
/Users/raul/tmp/php-zmq/zmq.c:238:20: error: expression is not assignable
                GC_REFCOUNT(&le) = 1;
                ~~~~~~~~~~~~~~~~ ^
/Users/x/tmp/php-zmq/zmq.c:526:53: warning: format specifies type 'long' but the argument has type 'zend_long' (aka 'long long') [-Wformat]
        return strpprintf(0, "zmq_socket:[%ld]-[%s]-[%d]", type, persistent_id->val, use_shared_ctx);
                                          ~~~              ^~~~
                                          %lld
/Users/x/tmp/php-zmq/zmq.c:538:19: error: expression is not assignable
        GC_REFCOUNT(&le) = 1;
        ~~~~~~~~~~~~~~~~ ^
2 warnings and 2 errors generated.
make: *** [zmq.lo] Error 1

**Comment by inikoo** [comment]
Ok [https://github.com/alexat/php-zmq](https://github.com/alexat/php-zmq)  works

I would suggest that @mkoppanen accept the pull request from alexat or http://zeromq.org/bindings:php instructions should point to that repository instead

**Comment by kvitozev** [comment]
@inikoo, do you have compiled (and working) version for x86 arch (vc15) of the extension?

**Comment by zebastian** [comment]
@inikoo alexats changes have been merged in 2018.
Please reopen, if you have problems with macos.

**Comment by Mark-H** [comment]
I'm getting the exact same errors as in this issue installing on Mac. It looks like `sudo pecl install zmq-beta` is trying to install v1.1.3 which [according to pecl is from 2016](http://pecl.php.net/package/zmq) - is that no longer the recommended way to install the [php bindings](http://wiki.zeromq.org/bindings:php)?

I'll try building from source next..

**Comment by ShawnJW** [comment]
I spent a half a day trying to get this to install correctly, as @inikoo stated the repository at https://github.com/alexat/php-zmq works when building on Mac.  I'm running macOS Catalina and using PHP 7.3
git clone https://github.com/alexat/php-zmq.git
` cd php-zmq
$ phpize && ./configure
$ make && make install`
