### ISSUE TITLE
configure: error: Unable to find libzmq installation

### ISSUE THREAD

**Issue by ghost** [zeromq/php-zmq#2]
Hi, when I'm trying to compile your package, I keep getting this error:

> phpize && ./configure
> Configuring for:
> PHP Api Version:         20041225
> Zend Module Api No:      20060613
> Zend Extension Api No:   220060519
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for a sed that does not truncate output... /bin/sed
> checking for gcc... gcc
> checking for C compiler default output file name... a.out
> checking whether the C compiler works... yes
> checking whether we are cross compiling... no
> checking for suffix of executables... 
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc and cc understand -c and -o together... yes
> checking for system library directory... lib
> checking if compiler supports -R... no
> checking if compiler supports -Wl,-rpath,... yes
> checking build system type... i686-pc-linux-gnu
> checking host system type... i686-pc-linux-gnu
> checking target system type... i686-pc-linux-gnu
> checking for PHP prefix... /usr
> checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
> checking for PHP extension directory... /usr/lib/php5/20060613+lfs
> checking for PHP installed headers prefix... /usr/include/php5
> checking for re2c... re2c
> checking for re2c version... 0.13.5 (ok)
> checking for gawk... no
> checking for nawk... nawk
> checking if nawk is broken... no
> checking whether to enable ZeroMQ support... yes, shared
> checking for pkg-config... no
> checking libzmq installation... configure: error: Unable to find libzmq installation

I have followed the installation guide to 0mq from here: http://www.zeromq.org/area:download-v20 with make and # make install . /usr/local/lib/ contains libzmq.a, libzmq.la, libzmq.so, libzmq.so.0 and libzmq.so.0.0.0 . I have also tried to run # ldconfig .

Can you help me?

**Comment by erlangparasu** [comment]
maybe this will help:
```bash
sudo apt install libzmq-ffi-perl
```

https://gist.github.com/erlangparasu/ce5b56707849a513d9e6ca5f6f097d6f

**Comment by dinbtechit** [comment]
On Macos, I do have `libzmq` but says `Unable to locate libzmq`. Is there any way to manually specify the location for pkg-config?

```
╰$ pkg-config libzmq --libs
-L/opt/homebrew/Cellar/zeromq/4.3.4/lib -lzmq
```

```
error: failed to run custom build command for `zmq-sys v0.11.0`

 cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'Unable to locate libzmq:
  pkg-config has not been configured to support cross-compilation.

  Install a sysroot for the target platform and configure it via
  PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a
  cross-compiling wrapper for pkg-config and set it via
  PKG_CONFIG environment variable.
```
