### ISSUE TITLE
Create tags/releases again

### ISSUE THREAD

**Issue by ahkok** [zeromq/php-zmq#211]
current latest release is 1.1.3 and years old (on pecl). There are no new tags in this repo.

I suggest getting back on the rails with tags in this repo. But it would be nice if releases to pecl could be made again as well.

**Comment by bluca** [comment]
This repository is without a maintainer, we are looking for one https://lists.zeromq.org/pipermail/zeromq-dev/2019-August/033109.html
Until someone volunteers, there will be no releases

**Comment by bluca** [comment]
duplicate of https://github.com/zeromq/php-zmq/issues/203
