### ISSUE TITLE
php7.4 / php7.3 on windows where I can found ZMQ DLL

### ISSUE THREAD

**Issue by faustynm** [zeromq/php-zmq#221]
Hi
On this page pecl.php.net/package/zmq/1.1.3/windows
I can download only for php 7.0 / 7.1 / 7.2 version.

Where I can found compiled files for windows for newer version of php

**Comment by cmb69** [comment]
zmq 1.1.3 is not compatible with PHP 7.3 and up. e0db82c3286da81fa8945894dd10125a528299e4 fixed that, but we cannot build Windows DLLs without a new release.

**Comment by cmb69** [comment]
It seems this is already covered by PR #203, so this ticket might be closed as duplicate.
