### ISSUE TITLE
extension zmq.so not found

### ISSUE THREAD

**Issue by flower4jyc** [zeromq/php-zmq#82]
I am binding php with zeromq and everything is ok but when i run my code with ZMQ and Ratchet
 ERROR:
Warning: PHP Startup: Unable to load dynamic library '/opt/lampp/lib/php/extensions/no-debug-non-zts-20100525/zmq.so' - /opt/lampp/lib/php/extensions/no-debug-non-zts-20100525/zmq.so: cannot open shared object file: No such file or directory in Unknown on line 0

Fatal error: Class 'React\ZMQ\Context' not found in /opt/lampp/htdocs/bin/push-server.php on line 8

and if i may ask where is zmq.so extension found

**Comment by tafelnl** [comment]
I am experiencing a similar problem.
From the error_log:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/cpanel/ea-php71/root/usr/lib64/php/modules/zmq.so' - /opt/cpanel/ea-php71/root/usr/lib64/php/modules/zmq.so: cannot open shared object file: No such file or directory in Unknown on line 0`

When I execute the command `find / -name zmq.so`
it spits out the following:

```
/usr/local/cpanel/3rdparty/php/72/lib/extensions/no-debug-non-zts-20170718/zmq.so
/root/php-zmq/modules/zmq.so
/root/php-zmq/.libs/zmq.so
```

As you can see I have cPanel installed.

On a side note: I am actually using PHP 7.1, but the first line suggests it is installed on PHP 7.2 (or am I wrong about this)

I am a complete newbie to installing things like this via root SSH, so please forgive me.

But what should I do next?

**Comment by tafelnl** [comment]
Update:
I copied 
`/usr/local/cpanel/3rdparty/php/72/lib/extensions/no-debug-non-zts-20170718/zmq.so`
to
`/opt/cpanel/ea-php71/root/usr/lib64/php/modules/zmq.so`

Rebooted the server, but it is still not working.

When I run the following commands:
```
# cd /opt/cpanel/ea-php71/root/usr/lib64/php/modules/
# ls
```
I see all installed modules. All are in green color. `zmq.so` is also listed, but colored white. I cannot seem to find out what this means.
Any ideas?
